# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 999ae79bafcc7388d207bfb2d5abd1defd8356b544fd47643faf9be9e471813c71f25279656157b9d8a352c671ec0fef90d7251f74ffbdb3622c0087213d8f54

test:
  secret_key_base: f2bfab1bd0140bba77e11a7600c6fa03ef11c298c03e998b5250a65627a71fe32a8f80fe07b851c2b7ccaf64b640714f22a79a4731abfd4263d685a2bad29bb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
